-- MadeGood Paid System — Supabase setup
-- Run this ONCE in the Supabase SQL Editor for the new paid-system project.
-- Has a `client` column throughout so adding more clients later is just data, not schema changes.

-- ── 1. Influencers (Master Lists INT + EXT) ───────────────────────────────────
create table if not exists public.paid_influencers (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  client           text not null default 'madegood',
  list_type        text not null default 'INT',   -- 'INT' or 'EXT'

  -- Personal info
  name             text,
  ig_handle        text,
  ig_url           text,
  tt_handle        text,
  tt_url           text,
  ig_followers     numeric,
  tt_followers     numeric,
  total_followers  numeric,
  tier             text,       -- Nano, Micro, Macro, Celeb
  vertical         text,
  archetype        text,
  location         text,
  gender           text,
  email            text,
  audience_age     text,       -- age breakdown notes
  shopmy_data      text,       -- ShopMy conversion notes

  -- EXT only
  external_feedback text,

  -- Outreach (tab 2 lives here, same record)
  outreach_status  text,       -- Contacted, No Response, Interested, Declined, etc.
  outreach_owner   text,       -- team member
  outreach_date    date,
  last_contact     date,
  outreach_notes   text,

  -- Pipeline flag
  in_paid_plan     boolean not null default false,

  -- Auto-flags
  is_international boolean generated always as (
    location is not null and
    lower(location) not like '%united states%' and
    lower(location) not like '%usa%' and
    lower(location) not like '%us%'
  ) stored
);

-- ── 2. Paid Plan ──────────────────────────────────────────────────────────────
-- One row per influencer × deliverable (an influencer can have multiple deliverables)
create table if not exists public.paid_plan (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  client              text not null default 'madegood',
  influencer_id       bigint references public.paid_influencers(id) on delete cascade,

  status              text,   -- 'In Negotiations', 'Offer Out', 'Locked'
  campaign            text,
  platform_format     text,   -- 'IG Reel', 'IG Story', 'IG In-Feed', 'TikTok'
  usage               text,   -- 'Organic', 'Paid', 'Both'
  exclusivity         text,

  -- Social URLs (can differ from master list if using specific posts)
  ig_url              text,
  tt_url              text,

  -- Impressions (inputs for cost calc)
  ig_reels_impressions numeric,
  ig_stories_impressions numeric,
  tt_impressions       numeric,

  -- CPM rates
  ig_reel_cpm         numeric,
  ig_story_cpm        numeric,
  ig_feed_cpm         numeric,
  tt_cpm              numeric,

  -- Usage rights
  organic_pct         numeric,
  paid_pct            numeric,

  -- Negotiation
  first_offer         numeric,
  influencer_offer    numeric,
  a8_counter          numeric,
  accepted_offer      numeric,

  notes               text
);

-- ── 3. Content Calendar ───────────────────────────────────────────────────────
create table if not exists public.content_calendar (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  client          text not null default 'madegood',
  influencer_id   bigint references public.paid_influencers(id) on delete cascade,
  paid_plan_id    bigint references public.paid_plan(id) on delete set null,

  scheduled_date  date,
  deliverable     text,   -- e.g. 'IG Reel', 'IG Story'
  usage           text,   -- 'Organic' / 'Paid'
  collab          boolean default false,
  notes           text
);

-- ── 4. Content Review ─────────────────────────────────────────────────────────
create table if not exists public.content_review (
  id                    bigint generated by default as identity primary key,
  created_at            timestamptz not null default now(),
  client                text not null default 'madegood',
  influencer_id         bigint references public.paid_influencers(id) on delete cascade,

  campaign              text,
  deliverable_type      text,
  content_due_date      date,
  live_date             date,
  month                 text,
  concept               text,

  content_v1            text,
  content_v2            text,
  caption_v1            text,
  caption_v2            text,
  a8_feedback_v1        text,
  a8_feedback_v2        text,
  client_feedback_v1    text,
  client_feedback_v2    text,
  approved_by_client    boolean default false,

  notes                 text
);

-- ── 5. Live Posts ─────────────────────────────────────────────────────────────
create table if not exists public.live_posts (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  client           text not null default 'madegood',
  influencer_id    bigint references public.paid_influencers(id) on delete cascade,

  live_date        date,
  campaign         text,
  final_rate       numeric,
  cogs             numeric,
  total_cost       numeric,
  utm_link         text,
  discount_code    text,
  raw_content_link text,
  live_link        text,
  contract_status  text,
  contract_link    text,
  ig_spark_code    text,
  tt_spark_code    text,
  content_boosted  boolean default false,
  organic_usage    boolean default false,
  paid_spend       numeric,

  -- Performance metrics
  total_views      numeric,
  ig_views         numeric,
  story_views      numeric,
  tt_views         numeric,
  likes            numeric,
  comments         numeric,
  shares           numeric,
  saves            numeric,

  notes            text
);

-- ── 6. Payment Status ─────────────────────────────────────────────────────────
create table if not exists public.payment_status (
  id                    bigint generated by default as identity primary key,
  created_at            timestamptz not null default now(),
  client                text not null default 'madegood',
  influencer_id         bigint references public.paid_influencers(id) on delete cascade,
  live_post_id          bigint references public.live_posts(id) on delete set null,

  agreed_rate           numeric,
  deliverables          text,
  content_live          boolean default false,
  payment_due_date      date,
  payment_date          date,
  status                text,   -- e.g. 'Awaiting Invoice', 'Approved', 'Paid'
  w9                    boolean default false,
  proper_invoice        boolean default false,
  added_to_quickbooks   boolean default false,
  paid                  boolean default false,

  notes                 text
);

-- ── Row-level security (open for the anon key — same pattern as other tools) ──
alter table public.paid_influencers  enable row level security;
alter table public.paid_plan         enable row level security;
alter table public.content_calendar  enable row level security;
alter table public.content_review    enable row level security;
alter table public.live_posts        enable row level security;
alter table public.payment_status    enable row level security;

create policy "Allow all" on public.paid_influencers  for all to anon, authenticated using (true) with check (true);
create policy "Allow all" on public.paid_plan         for all to anon, authenticated using (true) with check (true);
create policy "Allow all" on public.content_calendar  for all to anon, authenticated using (true) with check (true);
create policy "Allow all" on public.content_review    for all to anon, authenticated using (true) with check (true);
create policy "Allow all" on public.live_posts        for all to anon, authenticated using (true) with check (true);
create policy "Allow all" on public.payment_status    for all to anon, authenticated using (true) with check (true);
